// <auto-generated />
using DndApplication.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DndApplication.Server.Migrations
{
    [DbContext(typeof(DndDbContext))]
    [Migration("20240929210143_AddedCharacterIdToEquipment")]
    partial class AddedCharacterIdToEquipment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("DndApplication.Server.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Stefan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Olle"
                        });
                });

            modelBuilder.Entity("DndApplication.Server.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacterId = 1,
                            ItemId = "sword"
                        },
                        new
                        {
                            Id = 2,
                            CharacterId = 1,
                            ItemId = "shield"
                        },
                        new
                        {
                            Id = 3,
                            CharacterId = 2,
                            ItemId = "axe"
                        });
                });

            modelBuilder.Entity("DndApplication.Server.Models.Character", b =>
                {
                    b.OwnsOne("DndApplication.Server.Models.CharacterStat", "Stats", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Charisma")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Constitution")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Dexterity")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Intelligence")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Strength")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Wisdom")
                                .HasColumnType("INTEGER");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");

                            b1.HasData(
                                new
                                {
                                    CharacterId = 1,
                                    Charisma = 10,
                                    Constitution = 14,
                                    Dexterity = 12,
                                    Intelligence = 10,
                                    Strength = 15,
                                    Wisdom = 11
                                },
                                new
                                {
                                    CharacterId = 2,
                                    Charisma = 9,
                                    Constitution = 15,
                                    Dexterity = 13,
                                    Intelligence = 11,
                                    Strength = 16,
                                    Wisdom = 12
                                });
                        });

                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("DndApplication.Server.Models.Equipment", b =>
                {
                    b.HasOne("DndApplication.Server.Models.Character", "Character")
                        .WithMany("Equipments")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DndApplication.Server.Models.Character", b =>
                {
                    b.Navigation("Equipments");
                });
#pragma warning restore 612, 618
        }
    }
}
