// <auto-generated />
using DndApplication.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DndApplication.Server.Migrations
{
    [DbContext(typeof(DndDbContext))]
    [Migration("20240929204827_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("DndApplication.Server.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("DndApplication.Server.Models.Character", b =>
                {
                    b.OwnsOne("DndApplication.Server.Models.CharacterStat", "Stats", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Charisma")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Constitution")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Dexterity")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Intelligence")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Strength")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Wisdom")
                                .HasColumnType("INTEGER");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsMany("DndApplication.Server.Models.Equipment", "Equipments", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ItemId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("CharacterId", "Id");

                            b1.ToTable("Equipment");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("Equipments");

                    b.Navigation("Stats")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
