name: Build and Deploy Client to Azure Web App

on: 
    push:
        branches:
            - main 

jobs:
    build-and-deloy-client:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'
            - name: Fix node_modules permissions
              run: |
                sudo mkdir -p ./dndapplication.client/node_modules
                sudo chown -R $USER:$USER ./dndapplication.client/node_modules
            - name: Install dependencies
              run: |
                cd dndapplication.client
                npm ci
            - name: Build the project
              run: npm run build
              working-directory: dndapplication.client
            - name: 'Login to Azure'
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - name: 'Deploy to Azure Web App'   
              uses: azure/webapps-deploy@v2
              with:
                app-name: 'dndapplication'
                package: ./dndapplication.client/dist  # Changed from 'build' to 'dist'
                slot-name: 'production'
                publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
