name: Build and Deploy Client to Azure Web App

on: 
    push:
        branches:
            - main 

permissions:
    id-token: write
    contents: read

jobs:
    build-and-deploy-client:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'

            - name: Fix node_modules permissions
              run: |
                sudo mkdir -p ./dndapplication.client/node_modules
                sudo chown -R $USER:$USER ./dndapplication.client/node_modules

            - name: Install dependencies
              run: |
                cd dndapplication.client
                npm ci

            - name: Build the project
              run: npm run build
              working-directory: dndapplication.client

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Log in to Azure CLI
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Log in to Azure Container Registry
              run: |
                echo ${{ secrets.ACR_PASSWORD }} | docker login rognesrollspel.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

            - name: Build and push Docker image
              run: |
                cd dndapplication.client
                docker build -t rognesrollspel.azurecr.io/dndapplication-client:${{ github.sha }} .
                docker push rognesrollspel.azurecr.io/dndapplication-client:${{ github.sha }}

            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v2
              with:
                app-name: 'DndApplicationClient'
                images: 'rognesrollspel.azurecr.io/dndapplication-client:${{ github.sha }}'
