name: Deploy API

on:
  push:
    branches:
      - main
    # paths:
    #   - 'DndApplication.server/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'RPAPI'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_PUBLISH_API_PROFILE }}
          package: ./publish
