name: Build and Deploy Client to Azure Web App

on: 
    push:
        branches:
            - main 

jobs:
    build-and-deloy-client:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'
            - name: Install dependencies
              run: sudo npm install
              working-directory: ./dndapplication.client
            - name: Build the project
              run: sudo npm run build
              working-directory: ./dndapplication.client
            - name: 'Login to Azure'
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
            - name: 'Deploy to Azure Web App'   
              uses: azure/webapps-deploy@v2
              with:
                app-name: 'dndapplication'
                package: ./dndapplication.client/build
                slot-name: 'production'
                publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
